export default {
    "USA": [
        'California',
        'Texas',
        'Virginia',
        'Massachusetts',
        'Florida',
        'Maryland',
        'Louisiana',
        'Georgia',
        'Pennsylvania',
        'Arizona',
        'Colorado',
        'Michigan',
        'New Jersey',
        'North Carolina',
        'Vermont',
        'Illinois',
        'Alaska',
        'Missouri',
        'New Mexico',
        'Oklahoma',
        'Ohio',
        'Tennessee',
        'Delaware',
        'Alabama',
        'Arkansas',
        'Utah',
        'West Virginia',
        'Oregon',
        'Nevada',
        'South Dakota',
        'Wyoming',
        'Montana',
        'Idaho',
        'Indiana',
        'Iowa',
        'North Dakota',
        'New York',
        'Washington',
        'Kansas',
        'Kentucky',
        'Mississippi',
        'Hawaii',
        'Rhode Island',
        'Wisconsin',
        'Connecticut',
        'New',
        'Hampshire',
        'Nebraska',
        'South Carolina',
        'Minnesota',
        'Maine',
    ],
    "UK": [
        {name: 'London' , value: "London"},
        {name: 'Cardiff' , value: "Cardiff" },
        {name: 'British Overseas Territories' , value: "British Overseas Territories"},
        {name: 'British Empire' , value: "British Empire" },
        {name: 'British Antarctic Territory' , value: "British Antarctic Territory" },
    ],
    "India": [
        'kerala',
        'Maharashtra',
        'Tamil Nadu',
        'Karnataka',
        'Punjab',
        'Uttar Pradesh',
        'Rajasthan',
        'Jammu and',
        'Kashmir',
        'Gujarat',
        'Bihar',
        'Telangana',
        'Andhra Pradesh',
        'West Bengal',
        'Madhya Pradesh',
        'Odisha',
        'Assam',
        'Goa',
        'Haryana',
        'Jharkhand',
        'Manipur',
        'Himachal Pradesh',
        'Nagaland',
        'Chhattisgarh',
        'Uttarakhand',
        'Sikkim',
        'Arunachal Pradesh',
        'Meghalaya',
        'Tripura',
        'Mizoram',
    ],
    "Singapore": [
        'East side',
        'East central',
        'Central',
        'Central west',
        'West',
        'North east',
        'South west'
    ],
    "UAE": [
        'Abu Dhabi',
        'Dubai',
        'Sharjah',
        'Umm al-Qaiwain',
        'Fujairah',
        'Ajman',
        'Ra\'s al-Khaimah'
    ]
}